name: Deploy to IONOS Shared Hosting (SFTP)

on:
  push:
    branches: ["master"]

jobs:
  sftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy over SFTP
        uses: wangyucode/sftp-deploy@v2.0
        with:
          server: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: "./"              # local project folder
          remote_path: "/cloudchillies.com/test-php/"   # must end with /
          delete_remote_files: false    # keeps existing files
